### ISSUE TITLE
你的requirements.txt文件用不了

### ISSUE THREAD

**Issue by HuRuWo** [lateautumn4lin/arida#1]

**Comment by lateautumn4lin** [comment]
老哥是怎么用不来？报的什么错？

**Comment by tcc0lin** [comment]
> _No description provided._

老哥是怎么用不来？报的什么错？

**Comment by HuRuWo** [comment]
已经解决了  
你这项目挺有意思，不过可以做些改进变得更方便。

**Comment by tcc0lin** [comment]
> 已经解决了
> 你这项目挺有意思，不过可以做些改进变得更方便。

感谢大佬，回复得晚了，大佬可以提供些建议吗？
